version: '3.9'

services:
  medicohub-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medicohub-frontend
    ports:
      - '3000:80'
    environment:
      - EXPO_PUBLIC_API_URL=${EXPO_PUBLIC_API_URL:-http://localhost:4000/api}
    restart: unless-stopped
